- CHANGELOG.md
- gocd/Chart.yaml
Bump up GoCD Version to 20.8.0
> [GoCD Helm Chart] Bump up GoCD Version to 20.8.0

- gocd/Chart.yaml
- gocd/README.md
- gocd/templates/ingress.yaml
- gocd/values.yaml
This PR adds the ability to specify ingress paths and extra paths for each host.
This is required to add SSL redirection when using [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller).
See the [SSL redirection docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/tasks/ssl_redirect/). Both the existing base path must be set to /*, and an extra ssl-redirect path must be prepended.  
The logic added is in the same style as I have seen with other charts, such as [grafana](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L40).
Thanks!
> Add extra paths config

- CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 20.10.0

- CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 21.1.0

- CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 21.2.0

- gocd/templates/gocd-agent-deployment.yaml
- gocd/templates/gocd-server-deployment.yaml
- gocd/values.yaml
Added additional values to allow for custom labels for the server and agents.
Users have the ability to add pod specific and deployment specific labels.
> Add custom labels to Server and Agent

- .github/ct.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- gocd/Chart.yaml
- gocd/OWNERS
- gocd/README.md
- gocd/templates/ingress.yaml
- gocd/values.yaml
Fixes #16. 
- `networking.k8s.io/v1beta1` of `Ingress` is gone in `1.22`.
- `networking.k8s.io/v1` has been available since `1.19` but involves some changes as documented [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)
- Additionally `pathType` is now mandatory, however only [supported since Kubernetes 1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#better-path-matching-with-path-types).
These changes should be backward compatible, and mirror the way the new API serves up data created via the old API version.
Additionally
- removed redundant `nodeHttpsPort` which is no longer used by the chart
- added myself as maintainer
- Changed lint+test to run across multiple k8s versiobs
- Fixed test workflow to …
> Correct compatibility of Ingress for Kubernetes 1.22

- gocd/values.yaml
The example variable name should just be terminationGracePeriodSeconds.
Simply uncommenting the variable as is does not have the desired effect
> Fix example variable name

- CHANGELOG.md
- gocd/Chart.yaml
- gocd/README.md
- gocd/templates/gocd-server-deployment.yaml
- gocd/values.yaml
This should result in no changes to the chart output unless the priorityClassName is set in values.yaml. We would like this so that we can prioritize the server pod on our cluster.
> Add ability to set server priorityClassName

- CHANGELOG.md
- README.md
- gocd/Chart.yaml
- gocd/README.md
- gocd/ci/test-values.yaml
- gocd/templates/tests/gocd-test-config.yaml
- gocd/templates/tests/gocd-test.yaml
- gocd/values.yaml
- No longer creates the test config map by default; requiring opt-in with `tests.enabled=true` at install time to avoid cruft in people's clusters
- Switches to recently updated/patched Docker images rather than a special dev GoCD image
- Uses a Kubernetes Job rather than Pod, allowing for nicer cleanup of test resources after time
> Rework chart tests to use recent patched images

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/README.md
- gocd/templates/gocd-ea-service-account.yaml
- gocd/values.yaml
Added annotations to ServiceAccount .
ServiceAccount will be able to assume IAM Role in Amazon EKS.
re PR : https://github.com/gocd/helm-chart/pull/18
> Add ServiceAccount annotations

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 21.4.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
Switch to using a specific (validated) image digest during Helm test.
**Checklist**
> Avoid using :latest image during Helm test

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
Switched to a smaller Alpine testing image that works with BATS and doesn't require use of digests to lock.
**Checklist**
> Use smaller test image

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
Bumps Kubernetes Elastic Agent plugin version from 3.7.1 to 3.8.0
**Checklist**
> Bumps Kubernetes Elastic Agent plugin version from 3.7.1 to 3.8.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/templates/NOTES.txt
- gocd/templates/gocd-agent-deployment.yaml
- gocd/values.yaml
This typoed value was scheduled for removal 3 years ago, but probably forgotten. Should be perfectly safe to remove now.
**Checklist**
> Remove deprecated `agent.env.agentAutoRegisterEnvironemnts` value

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
Bumps Docker Registry Artifact plugin version from 1.1.0 to 1.3.0
**Checklist**
> Bumps Docker Registry Artifact plugin version from 1.1.0 to 1.3.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 22.1.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 22.2.0

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
Updates versions of testing tools and images to latest versions.
**Checklist**
> Bump versions of dependency tools/images

- .github/workflows/lint-test.yaml
Also revert to default kind version that comes with the action. They seem to be updating this in a timely fashion now.
> Bump K8s image versions

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 22.3.0

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/README.md
- gocd/templates/gocd-agent-deployment.yaml
- gocd/templates/gocd-server-deployment.yaml
- gocd/templates/ingress.yaml
- gocd/values.yaml
- Simplifies chart by requiring Kubernetes 1.20+ and dropping all outdated versions
- Changes defaults for persistent volumes to only check permissions on the root, which will speed start-ups for the vast majority of folks
**Possible challenges**
This is a breaking change - if you try and install the chart on Kubenetes 1.19 or earlier, it will fail validation
**Checklist**
> Drop compatibility with EOL Kubernetes versions

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
- Bumps pre-installed plugins to latest versions
- Tests against Kubernetes 1.26
- Bumps test tooling images to latest versions
**Checklist**
> Bump plugins and testing tools to latest versions

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/templates/configmap.yaml
- gocd/values.yaml
Bumps the two pre-installed plugins to their latest patched versions.
**Checklist**
> Bump bundled plugins to latest versions

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/templates/gocd-ea-cluster-role.yaml
These permissions seem unnecessary for the elastic agent plugin to function.
- nodes are not individually retrieved
- events do not appear to be watched
- namespaces are not retrieved like this
> Remove unnecessary ClusterRole permissions

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/templates/gocd-agent-deployment.yaml
There was an indentation misalignment in gocd-agent-deployment, which has been corrected.
**Relevant issues**
- Noting
**Possible challenges**
There is no possibility of breakage since the indentation is only corrected.
**Checklist**
> fix indent.

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 23.1.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/values.yaml
> Bump tool versions

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 23.2.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 23.3.0

- .github/workflows/lint-test.yaml
https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/
> Test against K8S 1.28

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 23.4.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 23.5.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 24.1.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 24.2.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 24.3.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/templates/gocd-agent-deployment.yaml
As noted in #106, the static agent health checks require additional configuration to work as they no longer listen on `0.0.0.0` by default for security reasons when running in other environments outside a Kubernetes pod sandbox.
This will automatically change the configuration if they are enabled.
**Relevant issues**
- fixes #106
**Checklist**
> Ensure static agents are listening on accessible ports when health checks enabled

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 24.4.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
- gocd/README.md
- gocd/values.yaml
Use a more actively maintained community image which is rapidly patched/updated for security vulnerabilities. See https://images.chainguard.dev/directory/image/bash/overview
> Switch to a Chainguard image for bash/curl style downloads

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 24.5.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 25.1.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 25.2.0

- gocd/CHANGELOG.md
- gocd/Chart.yaml
> [GoCD Helm Chart] Bump up GoCD Version to 25.3.0
